// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Package semconv maps Stripe API requests onto OpenTelemetry semantic
// conventions.
//
// It deliberately depends only on the standard library and OpenTelemetry, never
// on github.com/stripe/stripe-go. The hook package converts *stripe.Error into
// the version-neutral APIError below, so a new stripe-go major version only
// touches the hook, not this package.
package semconv

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	semconv "go.opentelemetry.io/otel/semconv/v1.37.0"
)

const (
	// DefaultServerAddress is the Stripe API host used when the request URL does
	// not carry one.
	DefaultServerAddress = "api.stripe.com"

	// IDPlaceholder replaces resource identifiers in templated URL paths.
	IDPlaceholder = "{id}"

	// MetricRequestDuration is the latency of a logical Stripe API request,
	// including any network retries the backend performs internally.
	MetricRequestDuration = "stripe.client.request.duration"

	// AttrRequestID carries the Stripe "Request-Id" response header, the value
	// Stripe support and the dashboard's request log key off.
	AttrRequestID = attribute.Key("stripe.request_id")
	// AttrErrorCode is stripe.Error.Code (e.g. "card_declined").
	AttrErrorCode = attribute.Key("stripe.error.code")
	// AttrErrorType is stripe.Error.Type (e.g. "card_error").
	AttrErrorType = attribute.Key("stripe.error.type")
)

// APIError is a version-neutral view of a Stripe API error. Zero values mean
// "not reported by Stripe" and are omitted from telemetry.
type APIError struct {
	StatusCode int
	Code       string
	Type       string
	RequestID  string
}

// Request describes one logical Stripe API request.
type Request struct {
	Method string
	// Path is the real request path, e.g. "/v1/customers/cus_NffrFeUfNV2Hib".
	Path string
	// ServerAddress is optional; defaults to DefaultServerAddress when empty.
	ServerAddress string
	// ServerPort is the resolved port, including the scheme default. Zero means
	// unknown and is omitted.
	ServerPort int
}

// SpanName returns the span name for a Stripe API request: the HTTP method plus
// the templated path, so it stays low-cardinality per OTel span-naming rules.
func SpanName(method, path string) string {
	method = normalizeMethod(method)
	tmpl := TemplatePath(path)
	if tmpl == "" {
		return method
	}
	return method + " " + tmpl
}

// TemplatePath replaces resource identifiers in a Stripe API path with
// IDPlaceholder, turning the unbounded set of real paths into the bounded set of
// API endpoints:
//
//	/v1/customers/cus_NffrFeUfNV2Hib/sources/card_1Mvo → /v1/customers/{id}/sources/{id}
//	/v1/payment_intents                                → /v1/payment_intents
//	/v2/core/events/evt_1Mvo                           → /v2/core/events/{id}
//
// ponytail: shape-based, not a route table. Stripe IDs whose value is chosen by
// the user rather than generated by Stripe (plan, coupon, product and SKU IDs
// such as /v1/coupons/summer) do not match the opaque-ID shape and pass through
// untemplated. Swap in a generated route table from Stripe's OpenAPI spec if
// that cardinality ever shows up in practice; a route table is the only way to
// close the gap, since "summer" is indistinguishable from a resource name.
func TemplatePath(path string) string {
	path = strings.TrimSpace(path)
	if path == "" {
		return ""
	}
	if i := strings.IndexAny(path, "?#"); i >= 0 {
		path = path[:i]
	}

	segments := strings.Split(path, "/")
	for i, seg := range segments {
		// Index 0 is empty for a rooted path; index 1 is the API version, and
		// the segment right after it always names a resource or namespace.
		if i <= 2 || seg == "" {
			continue
		}
		if isResourceID(seg) {
			segments[i] = IDPlaceholder
		}
	}
	return strings.Join(segments, "/")
}

// isResourceID reports whether a path segment looks like a Stripe-generated
// identifier rather than a resource or namespace name.
//
// Stripe generates IDs as a lowercase prefix, an underscore, and an opaque
// base62 token that in practice always contains a digit or an uppercase letter
// ("cus_NffrFeUfNV2Hib"). Resource names are lowercase words joined by
// underscores ("payment_intents"), so requiring a digit or uppercase letter
// after the prefix separates the two without a route table.
func isResourceID(seg string) bool {
	if seg == IDPlaceholder {
		return true
	}
	if allDigits(seg) {
		return true
	}
	prefix, token, ok := strings.Cut(seg, "_")
	if !ok || prefix == "" || token == "" || !isLowerAlpha(prefix) {
		return false
	}
	return hasDigitOrUpper(token)
}

func allDigits(s string) bool {
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return s != ""
}

func isLowerAlpha(s string) bool {
	for _, r := range s {
		if r < 'a' || r > 'z' {
			return false
		}
	}
	return s != ""
}

func hasDigitOrUpper(s string) bool {
	for _, r := range s {
		if (r >= '0' && r <= '9') || (r >= 'A' && r <= 'Z') {
			return true
		}
	}
	return false
}

func normalizeMethod(method string) string {
	method = strings.ToUpper(strings.TrimSpace(method))
	if method == "" {
		return "HTTP"
	}
	return method
}

func serverOrDefault(server string) string {
	if s := strings.TrimSpace(server); s != "" {
		return s
	}
	return DefaultServerAddress
}

// RequestTraceAttrs returns the attributes known before the request is sent.
func RequestTraceAttrs(req Request) []attribute.KeyValue {
	attrs := make([]attribute.KeyValue, 0, 4)
	attrs = append(attrs, semconv.HTTPRequestMethodKey.String(normalizeMethod(req.Method)))
	if tmpl := TemplatePath(req.Path); tmpl != "" {
		attrs = append(attrs, semconv.URLTemplate(tmpl))
		// The real path keeps resource IDs available on the span; only the
		// template is ever used for span names and metric labels.
		attrs = append(attrs, semconv.URLPath(strings.TrimSpace(req.Path)))
	}
	attrs = append(attrs, semconv.ServerAddress(serverOrDefault(req.ServerAddress)))
	if req.ServerPort > 0 {
		attrs = append(attrs, semconv.ServerPort(req.ServerPort))
	}
	return attrs
}

// ResponseTraceAttrs returns the attributes known once Stripe has responded.
func ResponseTraceAttrs(statusCode int, requestID string) []attribute.KeyValue {
	attrs := make([]attribute.KeyValue, 0, 2)
	if statusCode > 0 {
		attrs = append(attrs, semconv.HTTPResponseStatusCode(statusCode))
	}
	if id := strings.TrimSpace(requestID); id != "" {
		attrs = append(attrs, AttrRequestID.String(id))
	}
	return attrs
}

// ErrorTraceAttrs returns the attributes derived from a failed request.
//
// error.type is required by the HTTP client conventions whenever a request ends
// in error, so it is always set. See ErrorType for the precedence.
func ErrorTraceAttrs(err error, apiErr APIError) []attribute.KeyValue {
	if err == nil {
		return nil
	}
	attrs := make([]attribute.KeyValue, 0, 5)
	if apiErr.StatusCode > 0 {
		attrs = append(attrs, semconv.HTTPResponseStatusCode(apiErr.StatusCode))
	}
	attrs = append(attrs, semconv.ErrorTypeKey.String(ErrorType(err, apiErr)))
	if c := strings.TrimSpace(apiErr.Code); c != "" {
		attrs = append(attrs, AttrErrorCode.String(c))
	}
	if t := strings.TrimSpace(apiErr.Type); t != "" {
		attrs = append(attrs, AttrErrorType.String(t))
	}
	if id := strings.TrimSpace(apiErr.RequestID); id != "" {
		attrs = append(attrs, AttrRequestID.String(id))
	}
	return attrs
}

// ErrorType returns the value for error.type, most specific first:
//
//  1. the HTTP status code, when Stripe answered with one;
//  2. the Stripe error type, for v2 errors that carry no status code;
//  3. the Go error type, for transport failures that never reached Stripe
//     (e.g. "*url.Error"), which is low-cardinality as the convention
//     requires.
func ErrorType(err error, apiErr APIError) string {
	if apiErr.StatusCode > 0 {
		return strconv.Itoa(apiErr.StatusCode)
	}
	if t := strings.TrimSpace(apiErr.Type); t != "" {
		return t
	}
	if err != nil {
		return fmt.Sprintf("%T", err)
	}
	return "_OTHER"
}

// HTTPClientStatus returns the span status for an HTTP response status code,
// per the HTTP client semantic conventions: 4xx/5xx are errors, the rest unset.
func HTTPClientStatus(code int) (codes.Code, string) {
	if code < 100 || code >= 600 {
		return codes.Error, fmt.Sprintf("Invalid HTTP status code %d", code)
	}
	if code >= 400 {
		return codes.Error, ""
	}
	return codes.Unset, ""
}

// Metrics holds the Stripe client instruments.
type Metrics struct {
	requestDuration metric.Float64Histogram
}

// NewMetrics creates the Stripe client metrics. A nil meter yields no-op metrics.
func NewMetrics(meter metric.Meter) Metrics {
	m := Metrics{}
	if meter == nil {
		return m
	}
	var err error
	m.requestDuration, err = meter.Float64Histogram(
		MetricRequestDuration,
		metric.WithDescription("Duration of Stripe API requests, including internal network retries."),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10),
	)
	if err != nil {
		m.requestDuration = nil
	}
	return m
}

// MetricAttributes returns bounded-cardinality attributes for Stripe metrics.
//
// Included: server.address, server.port, http.request.method, url.template (the
// ~150 Stripe resource collections), http.response.status_code. Deliberately
// excluded: url.path and stripe.request_id. Both are unbounded, so they stay on
// spans.
func MetricAttributes(req Request, statusCode int) []attribute.KeyValue {
	attrs := make([]attribute.KeyValue, 0, 5)
	attrs = append(attrs, semconv.ServerAddress(serverOrDefault(req.ServerAddress)))
	if req.ServerPort > 0 {
		attrs = append(attrs, semconv.ServerPort(req.ServerPort))
	}
	attrs = append(attrs, semconv.HTTPRequestMethodKey.String(normalizeMethod(req.Method)))
	if tmpl := metricURLTemplate(req.Path); tmpl != "" {
		attrs = append(attrs, semconv.URLTemplate(tmpl))
	}
	if statusCode > 0 {
		attrs = append(attrs, semconv.HTTPResponseStatusCode(statusCode))
	}
	return attrs
}

// metricURLTemplate returns a stricter template than TemplatePath, kept only
// for the metric label.
//
// TemplatePath's shape heuristic cannot catch every user-chosen ID: values on
// endpoints such as /v1/coupons/summer or /v1/products/my-product don't look
// like a Stripe-generated ID, so TemplatePath leaves them untouched, and the
// resulting template is unbounded. That is tolerable on a span (one value per
// request, and url.path already carries the exact resource), but not on a
// metric label, where every distinct value becomes a permanent series.
//
// The unbounded case can only start at one place: the first segment after the
// fixed version/namespace/resource prefix, which is the sole point where a
// caller-supplied value can stand where a Stripe-generated ID was expected. If
// TemplatePath resolved that segment to IDPlaceholder, the request is
// confirmed to be addressing a real Stripe object, and everything after it
// (further IDs, or the small fixed vocabulary of sub-resource names) is kept
// as-is, matching TemplatePath exactly. If it did not, this stops right there
// instead of guessing, so a request the heuristic could not classify never
// contributes an unbounded label value.
func metricURLTemplate(path string) string {
	tmpl := TemplatePath(path)
	if tmpl == "" {
		return ""
	}
	segments := strings.Split(tmpl, "/")
	prefixLen := 3 // "", version, resource
	if len(segments) > 1 && segments[1] == "v2" {
		prefixLen = 4 // "", version, namespace, resource
	}
	if len(segments) <= prefixLen || segments[prefixLen] == IDPlaceholder {
		return tmpl
	}
	return strings.Join(segments[:prefixLen], "/")
}

// RecordRequestDuration records the duration of a logical Stripe API request.
func (m Metrics) RecordRequestDuration(ctx context.Context, seconds float64, req Request, statusCode int) {
	if m.requestDuration == nil {
		return
	}
	m.requestDuration.Record(ctx, seconds, metric.WithAttributes(MetricAttributes(req, statusCode)...))
}
