// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package setup

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"io/fs"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/dave/dst"
	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"
	"golang.org/x/mod/semver"

	"go.opentelemetry.io/otelc/tool/ex"
	"go.opentelemetry.io/otelc/tool/internal/ast"
	"go.opentelemetry.io/otelc/tool/internal/pkgload"
	"go.opentelemetry.io/otelc/tool/internal/rule"
	"go.opentelemetry.io/otelc/tool/util"
)

func removeImports(f *dst.File, importPaths map[string]bool) error {
	decls := make([]dst.Decl, 0, len(f.Decls))

	for _, decl := range f.Decls {
		genDecl, isGenDecl := decl.(*dst.GenDecl)
		if !isGenDecl || genDecl.Tok != token.IMPORT {
			decls = append(decls, decl)
			continue
		}

		specs := genDecl.Specs[:0]
		for _, spec := range genDecl.Specs {
			importSpec, isImportSpec := spec.(*dst.ImportSpec)
			if !isImportSpec {
				specs = append(specs, spec)
				continue
			}

			path, err := strconv.Unquote(importSpec.Path.Value)
			if err != nil {
				return ex.Wrapf(err, "failed to unquote import path %s", importSpec.Path.Value)
			}

			// skip the import we want to remove
			if _, removeImport := importPaths[path]; removeImport {
				continue
			}

			specs = append(specs, spec)
		}

		if len(specs) == 0 {
			// entire import decl became empty
			continue
		}

		genDecl.Specs = specs
		decls = append(decls, genDecl)
	}

	f.Decls = decls
	return nil
}

func generateDirective(opts PinOptions) string {
	args := []string{
		"//go:generate",
		"go",
		"tool",
		util.OtelcToolExe,
		"pin",
		"--generate",
	}

	if !opts.Prune {
		args = append(args, "--prune=false")
	}
	if opts.Validate {
		args = append(args, "--validate")
	}

	return strings.Join(args, " ")
}

func updateGenerateDirective(f *dst.File, opts PinOptions) {
	// Nothing passed? Do not touch the directive at all.
	if opts.Generate == nil {
		return
	}

	comments := make([]string, 0, len(f.Decs.Start.All()))
	for _, comment := range f.Decs.Start.All() {
		// Drop any existing otelc pin directive. We will either
		// regenerate it or remove it entirely.
		const goGenerateDirectivePrefix = "//go:generate go tool " + util.OtelcToolExe + " pin"
		if strings.HasPrefix(comment, goGenerateDirectivePrefix) {
			continue
		}

		comments = append(comments, comment)
	}

	if *opts.Generate {
		comments = append(comments, generateDirective(opts))
	}

	f.Decs.Start.Clear()
	f.Decs.Start.Append(comments...)
}

func generateOtelInstrumentationGo(imports map[string]bool, opts PinOptions) *dst.File {
	// Create a slice of import paths and sort them
	importPaths := make([]string, 0, len(imports))
	for path := range imports {
		importPaths = append(importPaths, path)
	}
	slices.Sort(importPaths)

	// Use the sorted import paths to create import specs
	importSpecs := make([]dst.Spec, 0, len(importPaths))
	for _, path := range importPaths {
		importSpecs = append(importSpecs, &dst.ImportSpec{
			Name: ast.Ident(ast.IdentIgnore),
			Path: &dst.BasicLit{
				Kind:  token.STRING,
				Value: strconv.Quote(path),
			},
		})
	}

	comments := ast.LineComments(
		"// This file is automatically generated by otelc pin for tracking instrumentations.",
		"// Additional instrumentation imports may be added manually.",
		"\n",
		"//go:build tools",
	)

	// If generate is explicitly enabled, or not set at all, include the //go:generate directive.
	if opts.Generate == nil || *opts.Generate {
		comments.Start.Append(generateDirective(opts))
	}

	return &dst.File{
		Name: ast.Ident("tools"),
		Decs: dst.FileDecorations{
			NodeDecs: comments,
		},
		Decls: []dst.Decl{
			&dst.GenDecl{
				Tok:   token.IMPORT,
				Specs: importSpecs,
			},
		},
	}
}

type yamlRule struct {
	Target       rule.Target `yaml:"target"`
	VersionRange string      `yaml:"version"`
}

func loadModuleRules(
	ctx context.Context,
	moduleDir, module, currentVersion string,
	loaded map[string][]yamlRule,
) error {
	return filepath.WalkDir(moduleDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return ex.Wrap(err)
		}

		if d.IsDir() {
			// Skip any submodules
			if path != moduleDir && util.PathExists(filepath.Join(path, goModFileName)) {
				return filepath.SkipDir
			}
			return nil
		}

		if !util.IsRuleFile(d.Name()) {
			return nil
		}

		data, readErr := os.ReadFile(path) //nolint:gosec // walking embedded rules from extractOtelcBundle
		if readErr != nil {
			return ex.Wrapf(readErr, "reading rule file %s", path)
		}

		doc, parseErr := rule.ParseFile(data)
		if parseErr != nil {
			return ex.Wrapf(parseErr, "parsing rule file %s", path)
		}
		if versionErr := checkRuleFileVersion(ctx, path, doc, currentVersion); versionErr != nil {
			return versionErr
		}

		for _, entry := range doc.Entries {
			var r yamlRule
			if decodeErr := entry.Node.Decode(&r); decodeErr != nil {
				return ex.Wrapf(decodeErr, "parsing rule %q in %s", entry.Name, path)
			}
			if r.Target.IsZero() {
				continue
			}
			if validateErr := r.Target.Validate(); validateErr != nil {
				return ex.Wrapf(validateErr, "validating target for rule %q in %s", entry.Name, path)
			}
			loaded[module] = append(loaded[module], r)
		}

		return nil
	})
}

func loadMinimalRules(
	ctx context.Context,
	rulesRoot, currentVersion string,
) (map[string][]yamlRule, error) {
	loaded := make(map[string][]yamlRule)

	err := filepath.WalkDir(rulesRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return ex.Wrap(err)
		}
		// rulesRoot is instrumentation/
		// We want to load rules for submodules within instrumentation/
		// Look for go.mod nested within instrumentation/
		if d.IsDir() || d.Name() != goModFileName || filepath.Dir(path) == rulesRoot {
			return nil
		}

		modFile, err := parseGoMod(path)
		if err != nil {
			return ex.Wrapf(err, "loading %s", path)
		}

		return loadModuleRules(ctx, filepath.Dir(path), modFile.Module.Mod.Path, currentVersion, loaded)
	})
	if err != nil {
		return nil, err
	}

	return loaded, nil
}

func ensureOtelcRequireVersion(f *modfile.File, version string) (bool, error) {
	if !semver.IsValid(version) || version == "v0.0.0" || module.IsPseudoVersion(version) {
		return false, nil
	}

	for _, req := range f.Require {
		if req.Mod.Path != util.OtelcRoot {
			continue
		}

		if semver.Compare(req.Mod.Version, version) >= 0 {
			return false, nil
		}
		break
	}

	if err := f.AddRequire(util.OtelcRoot, version); err != nil {
		return false, ex.Wrap(err)
	}

	return true, nil
}

func ensureOtelcRequire(moduleDir, version string) (bool, error) {
	goModPath := filepath.Join(moduleDir, goModFileName)
	data, err := os.ReadFile(goModPath)
	if err != nil {
		return false, ex.Wrap(err)
	}

	f, err := modfile.Parse(goModPath, data, nil)
	if err != nil {
		return false, ex.Wrap(err)
	}

	modified := false

	hasTool := false
	for _, tool := range f.Tool {
		if tool.Path == util.OtelcToolCmdRoot {
			hasTool = true
			break
		}
	}

	hasRequire := false
	for _, req := range f.Require {
		if req.Mod.Path == util.OtelcRoot {
			hasRequire = true
			break
		}
	}

	if !hasTool {
		if addErr := f.AddTool(util.OtelcToolCmdRoot); addErr != nil {
			return false, ex.Wrap(addErr)
		}
		modified = true
	}

	added, ensureErr := ensureOtelcRequireVersion(f, version)
	if ensureErr != nil {
		return false, ensureErr
	}
	modified = modified || added

	// Dev builds can't pin their own version, so a missing require stays
	// missing. Report it anyway so the caller tidies and go resolves one.
	if !modified {
		return !hasRequire, nil
	}

	if writeErr := writeGoMod(goModPath, f); writeErr != nil {
		return false, writeErr
	}

	return true, nil
}

func matchInstrumentationImports(
	deps []*Dependency,
	ruleset map[string][]yamlRule,
	warn func(msg string, args ...any),
) map[string]bool {
	imports := make(map[string]bool)

	// Record the first unresolved-version skip per instrumentation module.
	// Warnings are emitted after matching so we only complain when the module
	// was not imported by any other rule/dep (avoids false positives).
	skipped := make(map[string]unresolvedSkip)

	// Match only on target + version.
	for _, dep := range deps {
		for modPath, rules := range ruleset {
			for _, r := range rules {
				tm := instrumentationRuleMatchesDep(dep, r)
				if tm.isRoot {
					// always add root targets; they are further matched in setup
					imports[modPath] = true
					continue
				}
				if !tm.matched {
					continue
				}

				if !util.VersionInRange(dep.Version, r.VersionRange) {
					recordUnresolvedSkip(skipped, modPath, dep, r.VersionRange)
					continue
				}

				imports[modPath] = true
			}
		}
	}

	emitUnresolvedSkipWarnings(warn, imports, skipped)
	return imports
}

type unresolvedSkip struct {
	dep          string
	versionRange string
}

type instrumentationTargetMatch struct {
	matched bool
	isRoot  bool
}

// instrumentationRuleMatchesDep reports whether r's target matches dep.
// Targets that include $root always pin the instrumentation module; setup
// matches them precisely later. Other targets are matched without the root
// module paths, so an excluded $root excludes nothing here, which can only
// pin a module that setup then leaves unused.
func instrumentationRuleMatchesDep(dep *Dependency, r yamlRule) instrumentationTargetMatch {
	if r.Target.IncludesRoot() {
		return instrumentationTargetMatch{matched: true, isRoot: true}
	}
	return instrumentationTargetMatch{matched: r.Target.Matches(dep.ImportPath, nil)}
}

func recordUnresolvedSkip(
	skipped map[string]unresolvedSkip,
	modPath string,
	dep *Dependency,
	versionRange string,
) {
	if !unresolvedVersionSkip(dep.Version, versionRange) {
		return
	}
	if _, ok := skipped[modPath]; ok {
		return
	}
	skipped[modPath] = unresolvedSkip{
		dep:          dep.ImportPath,
		versionRange: versionRange,
	}
}

func emitUnresolvedSkipWarnings(
	warn func(msg string, args ...any),
	imports map[string]bool,
	skipped map[string]unresolvedSkip,
) {
	if warn == nil {
		return
	}
	for modPath, s := range skipped {
		if imports[modPath] {
			continue
		}
		warnUnresolvedVersionSkip(warn, s.dep, s.versionRange,
			"instrumentation", modPath,
		)
	}
}

// skipTidyMessage is logged when updateToolFile skips go mod tidy. Tests match
// on it, since a skipped tidy leaves nothing else behind.
const skipTidyMessage = "tool file and go.mod unchanged, skipping go mod tidy"

func updateToolFile(ctx context.Context, toolFile string, prunedImports map[string]bool, opts PinOptions) error {
	original, readErr := os.ReadFile(toolFile)
	if readErr != nil {
		return ex.Wrap(readErr)
	}

	p := ast.NewAstParser()

	f, parseErr := p.Parse(toolFile, parser.ParseComments)
	if parseErr != nil {
		return parseErr
	}

	if len(prunedImports) > 0 {
		if removeErr := removeImports(f, prunedImports); removeErr != nil {
			return removeErr
		}
	}

	updateGenerateDirective(f, opts)

	updated, printErr := ast.PrintFile(f)
	if printErr != nil {
		return printErr
	}

	toolFileChanged := !bytes.Equal(updated, original)
	if toolFileChanged {
		if writeErr := util.WriteFileAtomic(toolFile, updated); writeErr != nil {
			return writeErr
		}
	}

	goModChanged, ensureErr := ensureOtelcRequire(filepath.Dir(toolFile), util.Version)
	if ensureErr != nil {
		return ensureErr
	}

	// go mod tidy loads the whole module graph, so only run it when otelc
	// changed the tool file or go.mod, or go.sum is missing. Manual go.mod
	// edits are left for the user to tidy.
	goSumPath := filepath.Join(filepath.Dir(toolFile), "go.sum")
	if !toolFileChanged && !goModChanged && util.PathExists(goSumPath) {
		util.LoggerFromContext(ctx).DebugContext(ctx, skipTidyMessage, "toolFile", toolFile)
		return nil
	}

	return runModTidy(ctx, filepath.Dir(toolFile))
}

func validateRuleFiles(ctx context.Context, ruleFiles []string) error {
	for _, ruleFile := range ruleFiles {
		content, err := os.ReadFile(ruleFile)
		if err != nil {
			return ex.Wrapf(err, "reading %s", ruleFile)
		}
		doc, err := rule.ParseFile(content)
		if err != nil {
			return ex.Wrapf(err, "parsing rule file %s", ruleFile)
		}
		if err = checkRuleFileVersion(ctx, ruleFile, doc, util.Version); err != nil {
			return err
		}
		if _, err = doc.Rules(); err != nil {
			return err
		}
	}
	return nil
}

func updatePinnedProjects(
	ctx context.Context,
	toolFiles []string,
	opts PinOptions,
) (*PinResult, error) {
	logger := util.LoggerFromContext(ctx)
	prunedImports := make(map[string]map[string]bool, len(toolFiles))

	walkErr := walkInstrumentation(ctx, toolFiles,
		func(v *instrumentationVisit) (bool, error) {
			pruneImport := func(reason error) {
				logger.WarnContext(ctx, "invalid instrumentation import",
					"importPath", v.Config.ImportPath,
					"toolFile", v.ToolFile,
					"reason", reason)
				_, _ = fmt.Fprintf(
					os.Stderr,
					"Invalid instrumentation import %s from %s: %v\n",
					v.Config.ImportPath,
					v.ToolFile,
					reason,
				)

				// We only prune imports from root tool files.
				if opts.Prune && slices.Contains(toolFiles, v.ToolFile) {
					if prunedImports[v.ToolFile] == nil {
						prunedImports[v.ToolFile] = make(map[string]bool)
					}
					prunedImports[v.ToolFile][v.Config.ImportPath] = true
				}
			}

			if v.Config.Error != nil {
				if errors.Is(v.Config.Error, errNotInstrumentation) {
					pruneImport(v.Config.Error)
					return false, nil
				}

				// Environment/module resolution problem.
				return false, v.Config.Error
			}

			// Also validate that all rule files in the import are valid.
			if opts.Validate {
				if validateErr := validateRuleFiles(ctx, v.Config.RuleFiles); validateErr != nil {
					pruneImport(validateErr)
					return false, nil
				}
			}

			// Always recurse into nested tool files when they exist.
			return true, nil
		},
	)
	if walkErr != nil {
		return nil, walkErr
	}

	for _, toolFile := range toolFiles {
		if err := updateToolFile(ctx, toolFile, prunedImports[toolFile], opts); err != nil {
			return nil, err
		}
	}

	return &PinResult{}, nil
}

func generatePinnedProjects(ctx context.Context, moduleDirs map[string]bool, opts PinOptions) (*PinResult, error) {
	logger := util.LoggerFromContext(ctx)
	subcommand := opts.Subcommand
	if subcommand == "" {
		subcommand = subcmdBuild
	}

	// No tool file found? Try generating one.
	deps, findDepsErr := findDeps(ctx, subcommand, opts.Args)
	if findDepsErr != nil {
		return nil, findDepsErr
	}

	extractErr := extractOtelcBundle()
	if extractErr != nil {
		return nil, extractErr
	}

	ruleset, err := loadMinimalRules(
		ctx,
		filepath.Join(util.GetBuildTempDir(), unzippedInstDir),
		util.Version,
	)
	if err != nil {
		return nil, err
	}

	// We expect every built-in instrumentation module to be importable
	imports := matchInstrumentationImports(deps, ruleset, func(msg string, args ...any) {
		logger.WarnContext(ctx, msg, args...)
	})

	// Nothing to instrument? Warn and skip generating tool file.
	if len(imports) == 0 {
		_, _ = fmt.Fprintf(
			os.Stderr,
			"Warning: no instrumentations matched, checked %d dependencies. Skipping generating %s file.\n",
			len(deps),
			toolFileCanonical,
		)
		logger.WarnContext(ctx, "no instrumentations matched, skipping generating tool file")

		// Ok to re-use deps here, because we do not run "go mod tidy".
		return &PinResult{AllDeps: deps}, nil
	}

	// Generate otel.instrumentation.go file with imports for all matched rules.
	f := generateOtelInstrumentationGo(imports, opts)
	dirs := slices.Sorted(maps.Keys(moduleDirs))
	for _, moduleDir := range dirs {
		path := filepath.Join(moduleDir, toolFileCanonical)
		if writeErr := ast.WriteFileAtomic(path, f); writeErr != nil {
			return nil, ex.Wrapf(writeErr, "writing %s", path)
		}

		if _, ensureErr := ensureOtelcRequire(moduleDir, util.Version); ensureErr != nil {
			return nil, ensureErr
		}

		if syncErr := syncDeps(ctx, imports, moduleDir); syncErr != nil {
			return nil, syncErr
		}

		keepForDebug(ctx, path)
	}

	// Intentionally return an empty PinResult
	// Since we ran syncDeps, the dependencies may have been updated
	// Therefore, we want to ensure we rerun findDeps in setup phase.
	return &PinResult{}, nil
}

func prepareVendoredBuild(ctx context.Context, logger *slog.Logger, args []string) ([]string, error) {
	if !vendoringActive(ctx, util.GetOtelcWorkDir()) {
		return args, nil
	}

	logger.InfoContext(ctx, "vendored project detected; building with -mod=mod")

	if err := os.Setenv("GOFLAGS", forceModMod(os.Getenv("GOFLAGS"))); err != nil {
		return nil, ex.Wrapf(err, "forcing module mode for vendored build")
	}

	return rewriteModVendor(args), nil
}

type PinOptions struct {
	// Whether to prune invalid imports within otel.instrumentation.go
	Prune bool
	// Whether to validate that all imports in otel.instrumentation.go contain valid rule
	Validate bool
	// Whether to have a //go:generate directive in otel.instrumentation.go
	Generate *bool
	// Args passed to go build/install/test in findDeps
	Args []string
	// Subcommand passed to go in findDeps (defaults to "build")
	Subcommand string
	// ModuleDirs is the set of module directories to search for tool files
	// If empty, module directories will be found using opts.Args
	ModuleDirs map[string]bool
}

type PinResult struct {
	// AllDeps is a list of all dependencies found in the project (not just those with instrumentation).
	// It may not be always present, this can be used by later stages (setup) instead of
	// re-parsing compile commands again.
	AllDeps []*Dependency
}

// Pin generates or updates otel.instrumentation.go to pin instrumentation packages for the current module.
// It also returns a PinResult, which may optionally include a list of all dependencies found in the project
// (not just those with instrumentation). The PinResult can be used by later stages (setup) instead of
// re-parsing compile commands again.
func Pin(ctx context.Context, opts PinOptions) (*PinResult, error) {
	var result *PinResult
	err := withBuildLock(ctx, func(ctx context.Context) error {
		var pinErr error
		result, pinErr = pinLocked(ctx, opts)
		return pinErr
	})
	return result, err
}

func pinLocked(ctx context.Context, opts PinOptions) (*PinResult, error) {
	moduleDirs := opts.ModuleDirs
	// moduleDirs being empty means Pin was invoked as a standalone command
	// (not as part of a setup run), so use opts.Args to find module directories.
	if len(moduleDirs) == 0 {
		// For same reason as Setup, we have to check vendoring state before
		// forcing module mode and rewriting vendor/ paths to module mode.
		args, err := prepareVendoredBuild(ctx, util.LoggerFromContext(ctx), opts.Args)
		if err != nil {
			return nil, err
		}
		opts.Args = args

		// Use opts.Args to find module directories
		pkgs, getErr := getBuildPackages(ctx, opts.Args)
		if getErr != nil {
			return nil, getErr
		}

		moduleDirs, err = pkgload.FindModuleDirs(ctx, pkgs)
		if err != nil {
			return nil, err
		}
	}

	toolFiles, findToolErr := findToolFiles(moduleDirs)
	if findToolErr != nil {
		return nil, findToolErr
	}

	// Existing otel.instrumentation.go / otelc.tool.go files found?
	// Validate and update them in-place.
	if len(toolFiles) > 0 {
		return updatePinnedProjects(ctx, toolFiles, opts)
	}

	// Otherwise, infer instrumentations from the dependency graph and
	// generate fresh tool files.
	return generatePinnedProjects(ctx, moduleDirs, opts)
}

// autoPin is a convenience function that automatically tracks generated/modified files before calling Pin
// in order to restore them after the build completes.
func autoPin(ctx context.Context, moduleDirs map[string]bool, subcommand string, args []string) (*PinResult, error) {
	stateManager, found := stateManagerFromContext(ctx)
	if !found {
		return nil, ex.New("state manager not found in context")
	}

	backupFiles, getBackupErr := getBackupFiles(ctx, moduleDirs)
	if getBackupErr != nil {
		return nil, getBackupErr
	}
	if trackErr := stateManager.TrackAll(backupFiles...); trackErr != nil {
		return nil, trackErr
	}

	pinResult, pinErr := Pin(ctx, PinOptions{
		Prune:      true,
		Args:       args,
		Subcommand: subcommand,
		ModuleDirs: moduleDirs,
	})

	return pinResult, pinErr
}
