name: Check YAML Formatting

on:
  pull_request:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
  push:
    branches: [main]
    paths:
      - "**/*.yml"
      - "**/*.yaml"

permissions:
  contents: read

jobs:
  yaml-format:
    name: Check YAML Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
        with:
          go-version-file: go.mod
          cache: false
      - run: make lint/yaml
